package asavin.mvp.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import asavin.mvp.model.entity.painting.Canvas;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CANVAS".
*/
public class CanvasDao extends AbstractDao<Canvas, Long> {

    public static final String TABLENAME = "CANVAS";

    /**
     * Properties of entity Canvas.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BrandId = new Property(0, Long.class, "brandId", false, "BRAND_ID");
        public final static Property ImageResource = new Property(1, String.class, "imageResource", false, "IMAGE_RESOURCE");
        public final static Property Id = new Property(2, Long.class, "id", true, "_id");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Price = new Property(4, Long.class, "price", false, "PRICE");
    }


    public CanvasDao(DaoConfig config) {
        super(config);
    }
    
    public CanvasDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CANVAS\" (" + //
                "\"BRAND_ID\" INTEGER NOT NULL ," + // 0: brandId
                "\"IMAGE_RESOURCE\" TEXT NOT NULL ," + // 1: imageResource
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 2: id
                "\"NAME\" TEXT NOT NULL ," + // 3: name
                "\"PRICE\" INTEGER NOT NULL );"); // 4: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CANVAS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Canvas entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getBrandId());
        stmt.bindString(2, entity.getImageResource());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
        stmt.bindString(4, entity.getName());
        stmt.bindLong(5, entity.getPrice());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Canvas entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getBrandId());
        stmt.bindString(2, entity.getImageResource());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(3, id);
        }
        stmt.bindString(4, entity.getName());
        stmt.bindLong(5, entity.getPrice());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2);
    }    

    @Override
    public Canvas readEntity(Cursor cursor, int offset) {
        Canvas entity = new Canvas( //
            cursor.getLong(offset + 0), // brandId
            cursor.getString(offset + 1), // imageResource
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // id
            cursor.getString(offset + 3), // name
            cursor.getLong(offset + 4) // price
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Canvas entity, int offset) {
        entity.setBrandId(cursor.getLong(offset + 0));
        entity.setImageResource(cursor.getString(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setName(cursor.getString(offset + 3));
        entity.setPrice(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Canvas entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Canvas entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Canvas entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
