package asavin.mvp.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import asavin.mvp.model.entity.brand.Brand;
import asavin.mvp.model.entity.bucket.Bucket;
import asavin.mvp.model.entity.child.Coloring;
import asavin.mvp.model.entity.child.Feltpen;
import asavin.mvp.model.entity.child.Puzzle;
import asavin.mvp.model.entity.child.School;
import asavin.mvp.model.entity.child.Toy;
import asavin.mvp.model.entity.Frame.Frame;
import asavin.mvp.model.entity.guide.Guide;
import asavin.mvp.model.entity.hobbie.Burning;
import asavin.mvp.model.entity.hobbie.Decorating;
import asavin.mvp.model.entity.hobbie.Decoupage;
import asavin.mvp.model.entity.hobbie.Gilding;
import asavin.mvp.model.entity.hobbie.Quilling;
import asavin.mvp.model.entity.hobbie.Wallow;
import asavin.mvp.model.entity.painting.Brush;
import asavin.mvp.model.entity.painting.Canvas;
import asavin.mvp.model.entity.painting.Easel;
import asavin.mvp.model.entity.painting.Paint;
import asavin.mvp.model.entity.painting.Paper;
import asavin.mvp.model.entity.painting.Pencil;
import asavin.mvp.model.entity.sculpture.Sculptinside;
import asavin.mvp.model.entity.sculpture.Thread;
import asavin.mvp.model.entity.structure.ChildProduct;
import asavin.mvp.model.entity.structure.HobbieProduct;

import asavin.mvp.model.dao.BrandDao;
import asavin.mvp.model.dao.BucketDao;
import asavin.mvp.model.dao.ColoringDao;
import asavin.mvp.model.dao.FeltpenDao;
import asavin.mvp.model.dao.PuzzleDao;
import asavin.mvp.model.dao.SchoolDao;
import asavin.mvp.model.dao.ToyDao;
import asavin.mvp.model.dao.FrameDao;
import asavin.mvp.model.dao.GuideDao;
import asavin.mvp.model.dao.BurningDao;
import asavin.mvp.model.dao.DecoratingDao;
import asavin.mvp.model.dao.DecoupageDao;
import asavin.mvp.model.dao.GildingDao;
import asavin.mvp.model.dao.QuillingDao;
import asavin.mvp.model.dao.WallowDao;
import asavin.mvp.model.dao.BrushDao;
import asavin.mvp.model.dao.CanvasDao;
import asavin.mvp.model.dao.EaselDao;
import asavin.mvp.model.dao.PaintDao;
import asavin.mvp.model.dao.PaperDao;
import asavin.mvp.model.dao.PencilDao;
import asavin.mvp.model.dao.SculptinsideDao;
import asavin.mvp.model.dao.ThreadDao;
import asavin.mvp.model.dao.ChildProductDao;
import asavin.mvp.model.dao.HobbieProductDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig brandDaoConfig;
    private final DaoConfig bucketDaoConfig;
    private final DaoConfig coloringDaoConfig;
    private final DaoConfig feltpenDaoConfig;
    private final DaoConfig puzzleDaoConfig;
    private final DaoConfig schoolDaoConfig;
    private final DaoConfig toyDaoConfig;
    private final DaoConfig frameDaoConfig;
    private final DaoConfig guideDaoConfig;
    private final DaoConfig burningDaoConfig;
    private final DaoConfig decoratingDaoConfig;
    private final DaoConfig decoupageDaoConfig;
    private final DaoConfig gildingDaoConfig;
    private final DaoConfig quillingDaoConfig;
    private final DaoConfig wallowDaoConfig;
    private final DaoConfig brushDaoConfig;
    private final DaoConfig canvasDaoConfig;
    private final DaoConfig easelDaoConfig;
    private final DaoConfig paintDaoConfig;
    private final DaoConfig paperDaoConfig;
    private final DaoConfig pencilDaoConfig;
    private final DaoConfig sculptinsideDaoConfig;
    private final DaoConfig threadDaoConfig;
    private final DaoConfig childProductDaoConfig;
    private final DaoConfig hobbieProductDaoConfig;

    private final BrandDao brandDao;
    private final BucketDao bucketDao;
    private final ColoringDao coloringDao;
    private final FeltpenDao feltpenDao;
    private final PuzzleDao puzzleDao;
    private final SchoolDao schoolDao;
    private final ToyDao toyDao;
    private final FrameDao frameDao;
    private final GuideDao guideDao;
    private final BurningDao burningDao;
    private final DecoratingDao decoratingDao;
    private final DecoupageDao decoupageDao;
    private final GildingDao gildingDao;
    private final QuillingDao quillingDao;
    private final WallowDao wallowDao;
    private final BrushDao brushDao;
    private final CanvasDao canvasDao;
    private final EaselDao easelDao;
    private final PaintDao paintDao;
    private final PaperDao paperDao;
    private final PencilDao pencilDao;
    private final SculptinsideDao sculptinsideDao;
    private final ThreadDao threadDao;
    private final ChildProductDao childProductDao;
    private final HobbieProductDao hobbieProductDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        brandDaoConfig = daoConfigMap.get(BrandDao.class).clone();
        brandDaoConfig.initIdentityScope(type);

        bucketDaoConfig = daoConfigMap.get(BucketDao.class).clone();
        bucketDaoConfig.initIdentityScope(type);

        coloringDaoConfig = daoConfigMap.get(ColoringDao.class).clone();
        coloringDaoConfig.initIdentityScope(type);

        feltpenDaoConfig = daoConfigMap.get(FeltpenDao.class).clone();
        feltpenDaoConfig.initIdentityScope(type);

        puzzleDaoConfig = daoConfigMap.get(PuzzleDao.class).clone();
        puzzleDaoConfig.initIdentityScope(type);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        toyDaoConfig = daoConfigMap.get(ToyDao.class).clone();
        toyDaoConfig.initIdentityScope(type);

        frameDaoConfig = daoConfigMap.get(FrameDao.class).clone();
        frameDaoConfig.initIdentityScope(type);

        guideDaoConfig = daoConfigMap.get(GuideDao.class).clone();
        guideDaoConfig.initIdentityScope(type);

        burningDaoConfig = daoConfigMap.get(BurningDao.class).clone();
        burningDaoConfig.initIdentityScope(type);

        decoratingDaoConfig = daoConfigMap.get(DecoratingDao.class).clone();
        decoratingDaoConfig.initIdentityScope(type);

        decoupageDaoConfig = daoConfigMap.get(DecoupageDao.class).clone();
        decoupageDaoConfig.initIdentityScope(type);

        gildingDaoConfig = daoConfigMap.get(GildingDao.class).clone();
        gildingDaoConfig.initIdentityScope(type);

        quillingDaoConfig = daoConfigMap.get(QuillingDao.class).clone();
        quillingDaoConfig.initIdentityScope(type);

        wallowDaoConfig = daoConfigMap.get(WallowDao.class).clone();
        wallowDaoConfig.initIdentityScope(type);

        brushDaoConfig = daoConfigMap.get(BrushDao.class).clone();
        brushDaoConfig.initIdentityScope(type);

        canvasDaoConfig = daoConfigMap.get(CanvasDao.class).clone();
        canvasDaoConfig.initIdentityScope(type);

        easelDaoConfig = daoConfigMap.get(EaselDao.class).clone();
        easelDaoConfig.initIdentityScope(type);

        paintDaoConfig = daoConfigMap.get(PaintDao.class).clone();
        paintDaoConfig.initIdentityScope(type);

        paperDaoConfig = daoConfigMap.get(PaperDao.class).clone();
        paperDaoConfig.initIdentityScope(type);

        pencilDaoConfig = daoConfigMap.get(PencilDao.class).clone();
        pencilDaoConfig.initIdentityScope(type);

        sculptinsideDaoConfig = daoConfigMap.get(SculptinsideDao.class).clone();
        sculptinsideDaoConfig.initIdentityScope(type);

        threadDaoConfig = daoConfigMap.get(ThreadDao.class).clone();
        threadDaoConfig.initIdentityScope(type);

        childProductDaoConfig = daoConfigMap.get(ChildProductDao.class).clone();
        childProductDaoConfig.initIdentityScope(type);

        hobbieProductDaoConfig = daoConfigMap.get(HobbieProductDao.class).clone();
        hobbieProductDaoConfig.initIdentityScope(type);

        brandDao = new BrandDao(brandDaoConfig, this);
        bucketDao = new BucketDao(bucketDaoConfig, this);
        coloringDao = new ColoringDao(coloringDaoConfig, this);
        feltpenDao = new FeltpenDao(feltpenDaoConfig, this);
        puzzleDao = new PuzzleDao(puzzleDaoConfig, this);
        schoolDao = new SchoolDao(schoolDaoConfig, this);
        toyDao = new ToyDao(toyDaoConfig, this);
        frameDao = new FrameDao(frameDaoConfig, this);
        guideDao = new GuideDao(guideDaoConfig, this);
        burningDao = new BurningDao(burningDaoConfig, this);
        decoratingDao = new DecoratingDao(decoratingDaoConfig, this);
        decoupageDao = new DecoupageDao(decoupageDaoConfig, this);
        gildingDao = new GildingDao(gildingDaoConfig, this);
        quillingDao = new QuillingDao(quillingDaoConfig, this);
        wallowDao = new WallowDao(wallowDaoConfig, this);
        brushDao = new BrushDao(brushDaoConfig, this);
        canvasDao = new CanvasDao(canvasDaoConfig, this);
        easelDao = new EaselDao(easelDaoConfig, this);
        paintDao = new PaintDao(paintDaoConfig, this);
        paperDao = new PaperDao(paperDaoConfig, this);
        pencilDao = new PencilDao(pencilDaoConfig, this);
        sculptinsideDao = new SculptinsideDao(sculptinsideDaoConfig, this);
        threadDao = new ThreadDao(threadDaoConfig, this);
        childProductDao = new ChildProductDao(childProductDaoConfig, this);
        hobbieProductDao = new HobbieProductDao(hobbieProductDaoConfig, this);

        registerDao(Brand.class, brandDao);
        registerDao(Bucket.class, bucketDao);
        registerDao(Coloring.class, coloringDao);
        registerDao(Feltpen.class, feltpenDao);
        registerDao(Puzzle.class, puzzleDao);
        registerDao(School.class, schoolDao);
        registerDao(Toy.class, toyDao);
        registerDao(Frame.class, frameDao);
        registerDao(Guide.class, guideDao);
        registerDao(Burning.class, burningDao);
        registerDao(Decorating.class, decoratingDao);
        registerDao(Decoupage.class, decoupageDao);
        registerDao(Gilding.class, gildingDao);
        registerDao(Quilling.class, quillingDao);
        registerDao(Wallow.class, wallowDao);
        registerDao(Brush.class, brushDao);
        registerDao(Canvas.class, canvasDao);
        registerDao(Easel.class, easelDao);
        registerDao(Paint.class, paintDao);
        registerDao(Paper.class, paperDao);
        registerDao(Pencil.class, pencilDao);
        registerDao(Sculptinside.class, sculptinsideDao);
        registerDao(Thread.class, threadDao);
        registerDao(ChildProduct.class, childProductDao);
        registerDao(HobbieProduct.class, hobbieProductDao);
    }
    
    public void clear() {
        brandDaoConfig.clearIdentityScope();
        bucketDaoConfig.clearIdentityScope();
        coloringDaoConfig.clearIdentityScope();
        feltpenDaoConfig.clearIdentityScope();
        puzzleDaoConfig.clearIdentityScope();
        schoolDaoConfig.clearIdentityScope();
        toyDaoConfig.clearIdentityScope();
        frameDaoConfig.clearIdentityScope();
        guideDaoConfig.clearIdentityScope();
        burningDaoConfig.clearIdentityScope();
        decoratingDaoConfig.clearIdentityScope();
        decoupageDaoConfig.clearIdentityScope();
        gildingDaoConfig.clearIdentityScope();
        quillingDaoConfig.clearIdentityScope();
        wallowDaoConfig.clearIdentityScope();
        brushDaoConfig.clearIdentityScope();
        canvasDaoConfig.clearIdentityScope();
        easelDaoConfig.clearIdentityScope();
        paintDaoConfig.clearIdentityScope();
        paperDaoConfig.clearIdentityScope();
        pencilDaoConfig.clearIdentityScope();
        sculptinsideDaoConfig.clearIdentityScope();
        threadDaoConfig.clearIdentityScope();
        childProductDaoConfig.clearIdentityScope();
        hobbieProductDaoConfig.clearIdentityScope();
    }

    public BrandDao getBrandDao() {
        return brandDao;
    }

    public BucketDao getBucketDao() {
        return bucketDao;
    }

    public ColoringDao getColoringDao() {
        return coloringDao;
    }

    public FeltpenDao getFeltpenDao() {
        return feltpenDao;
    }

    public PuzzleDao getPuzzleDao() {
        return puzzleDao;
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

    public ToyDao getToyDao() {
        return toyDao;
    }

    public FrameDao getFrameDao() {
        return frameDao;
    }

    public GuideDao getGuideDao() {
        return guideDao;
    }

    public BurningDao getBurningDao() {
        return burningDao;
    }

    public DecoratingDao getDecoratingDao() {
        return decoratingDao;
    }

    public DecoupageDao getDecoupageDao() {
        return decoupageDao;
    }

    public GildingDao getGildingDao() {
        return gildingDao;
    }

    public QuillingDao getQuillingDao() {
        return quillingDao;
    }

    public WallowDao getWallowDao() {
        return wallowDao;
    }

    public BrushDao getBrushDao() {
        return brushDao;
    }

    public CanvasDao getCanvasDao() {
        return canvasDao;
    }

    public EaselDao getEaselDao() {
        return easelDao;
    }

    public PaintDao getPaintDao() {
        return paintDao;
    }

    public PaperDao getPaperDao() {
        return paperDao;
    }

    public PencilDao getPencilDao() {
        return pencilDao;
    }

    public SculptinsideDao getSculptinsideDao() {
        return sculptinsideDao;
    }

    public ThreadDao getThreadDao() {
        return threadDao;
    }

    public ChildProductDao getChildProductDao() {
        return childProductDao;
    }

    public HobbieProductDao getHobbieProductDao() {
        return hobbieProductDao;
    }

}
